version: '3.0'

services:
  nest-api:
    container_name: nest-server
    image: dmastag/202208-nest-server
    environment:
      - PORT=3333
    ports:
      - '3333:3333'
    restart: always
  app:
    container_name: app
    image: dmastag/202208-ionic-app
    ports:
      - "4200:80"
    restart: always
